import { ISO_3166_1_ALPHA2, resolveCountryCode } from "../shared/geo/countryCode";

/**
 * The journey card's band, and the one rule that decides which of a trip's
 * countries paints a flag.
 *
 * WHY A SEPARATE MODULE FROM `countryFlag.tsx`. That module's `FlagImg` loads
 * `https://flagcdn.com` at RUNTIME — right for the small chips it was written
 * for, wrong for the card band, where nothing may be fetched at build or at
 * runtime (owner, 2026-10-09). The band paints only files this repository
 * ships, so the two needs do not share a source. The network that stays in
 * `countryFlag.tsx` is why this module exists at all.
 *
 * THE SET IS THE APP'S OWN COUNTRY DOMAIN, DERIVED AND NOT REGISTERED. Which
 * files may the band paint? One per code in `ISO_3166_1_ALPHA2` — the very list
 * `resolveCountryCode` recognises a country name from — reached by the
 * convention `/flags/<cc>.svg`. There is no per-flag allow-list to keep in step,
 * so the way to give a country a flag is to add its code to that shared list and
 * run `scripts/vendor-flags.mjs`; a code in the domain with no shipped asset
 * fails `__tests__/flagAssets.test.ts` rather than painting a hole. A code the
 * domain excludes — a grouping code, a placeholder like `XX`, any two letters
 * that are not a country — is dropped.
 *
 * MECHANISM, SO A TRIP THAT DOES NOT EXIST YET IS RIGHT. Nothing here is stored.
 * `trip.countries` is derived per request in the backend
 * (`backend/src/routes/trips/tripCountries.ts`) and this module recomputes the
 * flags from it on EVERY render, so a trip created after this change draws its
 * flags with no migration, no backfill and no script to run. If the backend
 * ever stores the list instead, the flags still follow whatever it holds — this
 * module caches nothing a later edit could go stale against.
 *
 * A COUNTRY WITH NO ASSET IS DROPPED, NEVER GUESSED. No generic flag, no ISO
 * letters, no emoji, no colour: exactly the rule the codebase already applies
 * to a number it does not know. The card's own figures line still prints the
 * true country count, and when at least one flag IS drawn the band carries a
 * `title` saying how many were left out — the "dash with a reason" of
 * `ListSummaryStrip.tsx` and `TripCard`. The title now fires only for a country
 * that genuinely resolves to nothing or to a code outside the shipped set,
 * never for one dropped to hit a number, because there is no number to hit.
 *
 * ORDER IS POSITIONAL, NOT CHRONOLOGICAL. `bannerFlags` keeps the array order
 * it is handed, but that order only decides which flag reads as more prominent
 * (first = the light corner). A trip's `countries` is a SET, never a route: the
 * stored array is the user's own order and the derived one is sorted
 * alphabetically (`backend/src/routes/trips/tripCountries.ts`). The band must
 * never be read as first-visited-to-last.
 *
 * NO COUNT CAP, AND WHY. An earlier pilot capped the band at three flags. A
 * trip's countries are a set with no meaningful order, so a cap can only hide a
 * country chosen arbitrarily — and the owner's own five-country journeys were
 * exactly what it hid (owner, 2026-10-09). The band now draws every country the
 * trip names; legibility at five comes from the count-keyed ribbon seam in
 * `TripBandFlags.ribbonMask`, not from dropping anything. Past roughly ten the
 * ribbons stop reading as separate flags and the band becomes a dense wash, but
 * nothing is removed and the figures line still prints the true count.
 */

/**
 * Code → the URL the band paints, derived from the app's own country list.
 *
 * No literal list of countries lives here: the keys ARE `ISO_3166_1_ALPHA2`, so
 * this map cannot drift from the resolver that feeds it. The paths are absolute
 * (`/flags/…`) because `public/` is served from the site root by Vite and nginx
 * alike; each asset carries its provenance and licence in a header comment, and
 * the whole set is regenerated by `scripts/vendor-flags.mjs`.
 */
export const BUNDLED_FLAGS: Readonly<Record<string, string>> = Object.fromEntries(
  ISO_3166_1_ALPHA2.map((cc) => [cc, `/flags/${cc.toLowerCase()}.svg`])
);

export interface BannerFlag {
  /** The resolved ISO 3166-1 alpha-2 code. */
  cc: string;
  /** Where the band paints it from — always a local asset. */
  url: string;
}

/** The asset URL for a code in the app's domain, or null when none ships. */
export function flagAssetUrl(cc: string): string | null {
  return BUNDLED_FLAGS[cc.trim().toUpperCase()] ?? null;
}

/**
 * The distinct countries a trip records, resolved to codes, in array order.
 *
 * Each entry runs through `resolveCountryCode`, which takes a code OR a name
 * in any language and returns `null` for anything it cannot identify — a wrong
 * flag being worse than none (`countryFlag.tsx`). Nulls are dropped and
 * duplicates collapsed, so this is the trip's true country SET, the number the
 * band's `title` counts against.
 */
export function knownCountries(countries: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const entry of countries) {
    const cc = resolveCountryCode(entry);
    if (!cc || seen.has(cc)) continue;
    seen.add(cc);
    out.push(cc);
  }
  return out;
}

/**
 * The drawable flags for a trip's band. Pure: same input, same output, no
 * network and no trip name — every journey renders this way by construction.
 *
 * Resolve → drop the undrawable → keep the rest, in order. There is no cap, so
 * the result is every country the trip names that has a shipped asset. `allow`
 * is injectable only so a test can pin the drop rule against a code the domain
 * excludes, without needing a real country to be missing an asset; production
 * always uses the default, which is the single seam the app reads.
 */
export function bannerFlags(
  countries: readonly string[],
  allow: Readonly<Record<string, string>> = BUNDLED_FLAGS
): BannerFlag[] {
  const out: BannerFlag[] = [];
  for (const cc of knownCountries(countries)) {
    const url = allow[cc];
    if (!url) continue;
    out.push({ cc, url });
  }
  return out;
}
