/*
 * GENERATED by scripts/generate-theme.mjs from design/tokens.json (v0.8.0-runde29).
 * Do not edit by hand — run `npm run tokens`.
 *
 * The canvas half of the theme. Everything the browser paints reads
 * `tokens.css`; deck.gl and the globe cannot, so they read this.
 */

export const tokens = {
  "color": {
    "bg": "#0b0d10",
    "canvas": "#07090c",
    "surface": "#14181d",
    "surface2": "#101317",
    "tile": "#1a1f26",
    "heroGradient": "linear-gradient(160deg,#171c22,#12161b)",
    "tabbarBg": "rgba(16,20,24,0.96)",
    "border": "rgba(231,227,220,0.12)",
    "text": "#e7e3dc",
    "textBright": "#f4ece0",
    "muted": "rgba(231,227,220,0.6)",
    "faint": "rgba(231,227,220,0.45)",
    "accent": "#f0a947",
    "accentText": "#0b0d10",
    "accentHover": "#f6bd66",
    "accentPressed": "#d8952f",
    "good": "#5ec2b2",
    "live": "#5ec2b2",
    "bad": "#e65a4f",
    "info": "#6fa0d6",
    "warn": "#d8952f",
    "paper": "#f5f1e8",
    "paperText": "#2a2419",
    "paperAccent": "#8a5213",
    "proBg": "rgba(240,169,71,0.15)",
    "proText": "#f0a947"
  },
  "domainColor": {
    "flight": "#f0a947",
    "cruise": "#4aa6b0",
    "hotel": "#5ec2b2",
    "poi": "#e7e3dc",
    "tour": "#f0a947",
    "roadtrip": "#f0a947",
    "rail": "#a597e8",
    "rental": "#d98cb3"
  },
  "statusColor": {
    "pending": "#6fa0d6",
    "scheduled": "#6fa0d6",
    "flown": "#5ec2b2",
    "cancelled": "#e65a4f",
    "historical": "rgba(231,227,220,0.62)",
    "duplicated": "#d8952f",
    "guess": "#d8952f",
    "review": "#d8952f"
  },
  "tierColor": {
    "bronze": "#f59e0b",
    "silver": "rgba(231,227,220,0.62)",
    "gold": "#f0a947",
    "platinum": "#22d3ee",
    "diamond": "#a855f7"
  },
  "chartColors": [
    "#f0a947",
    "#6fa0d6",
    "#5ec2b2",
    "#bc8cff",
    "#f778ba",
    "#d8952f",
    "#e65a4f",
    "#9ec0e8"
  ],
  "chartMutedBar": "#2a2f36",
  "listColor": {
    "slate": "#8fa3b8",
    "sand": "#d9b382",
    "rose": "#e88fa8",
    "violet": "#bc8cff",
    "sky": "#8ec5f0",
    "mint": "#7fd6b8",
    "amberSoft": "#e0b366",
    "coral": "#ef9a86",
    "teal": "#5fb3bf",
    "lime": "#a8cf76"
  },
  "map": {
    "chrome": "floating",
    "toolbarCell": 44,
    "toolbarRadius": 14,
    "attribution": "mono 10 muted",
    "summaryFont": "mono 10 tracking .1em",
    "plannedStroke": "dashed info",
    "flownStroke": "accent"
  }
} as const;

export type Rgb = [number, number, number];

/** `#f0a947` → `[240, 169, 71]`. Only ever called on a token value. */
export function rgb(hex: string): Rgb {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
